backend:
  name: github
  repo: TonyMontanaIT/italyscasa-content
  branch: main
  site_domain: italyscasa-content.netlify.app
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "blog-{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Tipo", name: "tipo", widget: "string" }
      - { label: "H1", name: "h1", widget: "text" }
      - { label: "h2t1", name: "h2t1", widget: "text" }
      - { label: "text1", name: "text1", widget: "text" }
      - { label: "h2t2", name: "h2t2", widget: "text" }
      - { label: "text2", name: "text2", widget: "text" }
      - { label: "h2t3", name: "h2t3", widget: "text" }
      - { label: "text3", name: "text3", widget: "text" }
      - { label: "h2t4", name: "h2t4", widget: "text" }
      - { label: "text4", name: "text4", widget: "text" }
      - { label: "h2t5", name: "h2t5", widget: "text" }
      - { label: "text5", name: "text5", widget: "text" }
      - { label: "h2t6", name: "h2t6", widget: "text" }
      - { label: "text6", name: "text6", widget: "text" }
      - { label: "Phone", name: "phone", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
