name: Generate and Translate Blog JSON

on:
  push:
    paths:
      - 'blog/*.md'
      - 'generate_json.py'
      - 'generate_structured_blog.js'
      - 'translate_blog.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter requests

      - name: Generate index.json and structured-blog.json
        run: |
          python generate_json.py
          node generate_structured_blog.js

      - name: Translate index.json
        run: python translate_blog.py

      - name: Commit and push ALL changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull origin main --rebase || echo "Nothing to pull"
          git add blog/index.json blog/structured-blog.json blog/index_translated.json
          git commit -m "🔁 Update ALL blog JSON files" || echo "No changes to commit"
          git push origin HEAD:main
