
name: Update index.json and structured-blog.json from Markdown

on:
  push:
    paths:
      - 'blog/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-frontmatter

      - name: Generate index.json and structured-blog.json
        run: |
          python generate_json.py
          python generate_structured_blog.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add blog/index.json blog/structured-blog.json
          git commit -m "Update blog JSON files [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
