name: Update index2.json from Markdown

on:
  push:
    paths:
      - 'anunci/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-frontmatter

      - name: Generate index2.json
        run: python generate_annunci_json.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add anunci/index2.json
          git commit -m "Update index2.json [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
